# Thanks to Dimuthu Wickramanyake
# https://medium.com/nerd-for-tech/react-with-typescript-series-charity-web-app-deploying-to-github-pages-ab86a1888fab
name: React Build

on:
  push:
    branches: [ "main" ]

env:
  CI: false
  USE_HASH_ROUTER: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'
      actions: 'write'
      checks: 'write'
      deployments: 'write'
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup_node
        with:
          node-version: ${{ matrix.node-version }}
          npm-auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build
        run: |
          yarn install
          yarn run dev:build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload build directory content
          path: 'build/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
