name: Cypress testing

on:
  pull_request:
    branches: [ "main" ]

env:
  USE_GITHUB_PAGES: true

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run component tests
        uses: cypress-io/github-action@v6
        with:
          component: true
      - name: Cypress run e2e tests, chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: yarn dev:build
          start: yarn dev:start
          wait-on: "http://localhost:3000"
      - name: Cypress run e2e tests, firefox
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          build: yarn dev:build
          start: yarn dev:start
          wait-on: "http://localhost:3000"

