name: Cypress testing

on:
  pull_request:
    branches: [ "main" ]

env:
  USE_HASH_ROUTER: true

jobs:
  cypress-run-component:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/setup-node.yml
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run component tests
        uses: cypress-io/github-action@v6
        with:
          component: true

  cypress-run-e2e:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        browser: [ 'chrome', 'firefox' ]
    steps:
      - uses: ./.github/workflows/setup-node.yml
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cypress run e2e tests
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          build: yarn dev:build
          start: yarn dev:start
          wait-on: "http://localhost:3000"

