on:
  pull_request:

jobs:
  tsc-and-lint:
    name: Check TypeScript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: ./.github/workflows/setup-node
      - name: Setup node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn install
          yarn run dev:tsc

  lint:
    name: Run eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: ./.github/workflows/setup-node
      - name: Setup node
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn install
          yarn run dev:lint
