on:
  pull_request:

jobs:
  tsc-and-lint:
    name: Check TypeScript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: huh
        uses: actions/checkout@v4
        run: ls -al ./.github/actions
      - uses: ./.github/actions/setup-node.yml
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn install
          yarn run dev:tsc

  lint:
    name: Run eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: ./.github/actions/setup-node.yml
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: |
          yarn install
          yarn run dev:lint
